baseURL = 'https://togather-foundation.github.io/website/'
languageCode = 'en-us'
title = 'Togather Foundation'
theme = 'minimal'
ignoreLogs = ['warning-goldmark-raw-html']

[params]
description = 'An open ecosystem for community-owned event discovery'

[markup.goldmark.renderer]
unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'